### ISSUE TITLE
Minor issue with delivery of trailer in Transportation job

### ISSUE THREAD

**Issue by essjaybee** [InZidiuZ/op-framework-bug-tracker#119] opened 2019-06-29 17:49 UTC
**Reporter:**
OMGPointless#1823

**Summary:**
This is a minor issue, and there are steps around. Not sure if it's worth putting time on, but perhaps it's a minor one so here we go anyway.
If you take a job as a Transporter. You pick up your trailer, go to the gas station to fill up gas. If you on the way to the gas station detach your trailer (for some narrow corners), and then proceed by being a dumbass and drive away from the gas station without your trailer. Your mission is a goner. Obviously it depends on how far you drive before it's an issue, so I assume it's distance based with the vehicle being despawned for me, and then respawning when I come back. 

This last time I was ~2 blocks away when I went "shit". Effects are that the marker is still there, your trailer will show up where you last left it, but when you go to your target destination there is no red marker so you have to dump the trailer, /canceljob and wait the 10 minutes. 

**Steps to Reproduce:**
* Get transporter job
* Get a route, take trailer and go somewhere with it, on your way to your destination.
* Detach trailer and drive away for a block or two, and come back.
* Your trailer shouldn't be accepted at destination.

**Expected Results:**
Trailer accepted.

**Actual Results:**
Trailer not accepted cus there is no red arrow to interact with and nothing to pops that says to push E.

## Additional Information

**Screenshots:**
Not adding F8 log as there is nothing there, went through it all.

**Game Resolution:**
Most likely irrelevant

**Player Data:**
![20190629194725_1](https://user-images.githubusercontent.com/2750716/60387667-e47a9c00-9aa6-11e9-888b-c52b996933ff.jpg)

**Notes:**
You da man, just close it if you don't feel like fixing it right now. The obvious fix is "just don't freaking forget your trailer dummy". but maybe there are situations that calls for it. 

Edit: Oh and sorry for not having more screenshots. I've managed to do this 4 times now over the past few days, wasn't gonna bother reporting it at first.

**Comment by InZidiuZ** [comment] 2019-06-29 18:09
Hey,

So I tried reproducing it. At first, I quickly just unhooked it & hooked it on again, it got accepted. Then I repeated your steps with also driving away from it, and it still did accept it.

Now guessing it's network-related, I check the code & found a setting which would allow other clients to take ownership of the entity/vehicle. My *hypothesis* is that another client, most likely nearby, would take ownership over the vehicle as soon as you're away from it, which would let your client delete the vehicle as you no longer need it. But as soon as you come back, it would spawn it again, but this time with a new vehicle-identifier, preventing the drop-off from accepting it.

I disabled the part that lets other clients take control over it, but of course, this is just my theory as to what is happening. If this doesn't end up resolving the issue, please comment here again so I can use a different identifier (such as plate number) to decide whether the trailer should be accepted or not.

*and yes, pls screenshots, not enough screenshots is like reading a book without pictures, and who tf does that ;)*

**InZidiuZ**
*OP-FW Developer*

**Closed by InZidiuZ** 2019-06-29 18:09 UTC
Labels: bug

**Comment by essjaybee** [comment] 2019-06-29 18:13
Hahaha, I knooow. Next time I catch myself doing it I'll screenshot the whole process and get numbers as to how far I was away etc. But I think your analysis of what happens is probably right, my gut feeling was that it would spawn again when I come back, but with a different identifier or missing flag or something, which would then not be recognized at drop-off.

I'm pretty sure I'll do it again soon enough, I'll report back. And thanks a lot!

**Comment by Racermon** [comment] 2019-07-02 07:34
Created an account just to give an update on this, I had a failure on one of my deliveries to this location 
![1](https://user-images.githubusercontent.com/52444405/60492940-8fd74c80-9c71-11e9-8bdc-3c261e939ddc.png)
What I had done before I gave up was head to the mechanic just south of there, I went inside and came back out, I'm not sure if I hooked up my trailer but I don't think I did (yet) because I walked over to someone across the street a bit down the road, I'm not sure if it would have been out of that distance you mentioned about the vehicle getting an id or w/e but this was my instance of the job failing
