### ISSUE TITLE
Fix Garbage Job

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/op-framework-bug-tracker#50] opened 2019-06-21 21:37 UTC
Suggester:
Blankey

Summary:
Garbage Job will randomly cycle through all the 'trash pickups' once you reach your job destination. It'll force you back to the job start and it is super annoying because it wastes your time driving halfway across a city just for no reason.

Reason:
?? Idk ??

Economy:
Make the job actually playable.

**Comment by InZidiuZ** [comment] 2019-06-23 00:21
Please include a screenshot of /info, and also a few screenshots of your F8 console just after entering a pick-up destination. Addition information such as how many players are online at the time, if you saw anyone else in your area, and if it's the first time doing the job after logging on the server, or not, would be useful.

**Comment by BlankeyBoi** [comment] 2019-06-23 15:27
![image](https://user-images.githubusercontent.com/49964391/59978383-ba5a4300-95a9-11e9-89f2-fa6c278ebe82.png)
![image](https://user-images.githubusercontent.com/49964391/59978386-c0e8ba80-95a9-11e9-8c8f-6d880b43dc70.png)
![image](https://user-images.githubusercontent.com/49964391/59978391-c7773200-95a9-11e9-8b34-68190fb56074.png)
31 players online
No one around me - Used Admin menu to spectate.
This is the second time doing the job. It happened the first time as well.

**Comment by BlankeyBoi** [comment] 2019-06-23 15:42
And, just for added help here is a 'successful' trip. It let me get about 4 but then buzzed through the last couple and told me to go back to HQ. So it kinda half-worked.
![image](https://user-images.githubusercontent.com/49964391/59978583-e7a7f080-95ab-11e9-934e-6cb27cb8fdc9.png)
![image](https://user-images.githubusercontent.com/49964391/59978589-f1c9ef00-95ab-11e9-916f-edfabffd76b1.png)

**Comment by InZidiuZ** [comment] 2019-06-23 16:33
Very strange... I've made some changes to it, but not exactly sure what's causing it, so we'll have to see if the next patch resolves anything.

**Comment by essjaybee** [comment] 2019-06-23 16:39
Yup! Had this too when I tried out garbage.

Went to job, got the truck and went to my location.
Heard a bunch of pings, managed to pick up one of the trash cans and place it in the truck, got back in and ping ping ping and then "RETURN TO HQ" and the pinging continued.
Return to HQ and get my $70.

Take out a new truck, get to the place, ping ping ping, return to HQ.
Same on third trial although one of the garbage things managed to get stuck on my hand.

If this hasn't been resolved yet I'd gladly do more testing and will paste F8 log, didn't cross my mind at the time as I was just trying out the jobs.

**Comment by BlankeyBoi** [comment] 2019-06-23 23:16
Still broken @InZidiuZ </3

**Comment by InZidiuZ** [comment] 2019-06-23 23:32
Need screenshots of your F8 console still

**Comment by BlankeyBoi** [comment] 2019-06-23 23:32
![image](https://user-images.githubusercontent.com/49964391/59983449-a59f9e80-95ed-11e9-8d01-aa2f27e8fb61.png)

**Comment by InZidiuZ** [comment] 2019-06-23 23:35
That one didn't find enough objects, so it did as intended there. Do another few tries, and take more screenshots.

**Comment by BlankeyBoi** [comment] 2019-06-23 23:38
I'll do 5 trips here in a bit and give you a sc of each one.

**Comment by BlankeyBoi** [comment] 2019-06-23 23:40
Also, in regard to the 'didn't find enough objects' thing It was in the middle of me running to another trash with an icon above it. It merely told me 'return to HQ' while I was walking up to the trash, for no reason.

**Comment by BlankeyBoi** [comment] 2019-06-24 00:12
Trip 1:
Distance: 0.68m
Instant 'Return to HQ' - Hadn't even got out of the truck yet.
Its shows the trash arrow, but picking up the trash forces you to hold it forever (OR until you start a new trip and get a new piece of trash to override it.)
![image](https://user-images.githubusercontent.com/49964391/59983623-03cd8100-95f0-11e9-8558-da7a3b0d3180.png)

Trip 2: 
Distance 0.68m
Instant 'Return to HQ' - Hadn't even got out of the truck yet.
![image](https://user-images.githubusercontent.com/49964391/59983668-72aada00-95f0-11e9-8a75-64fba9434627.png)
(Picture of Trash with icon and 'Return to HQ')
![image](https://user-images.githubusercontent.com/49964391/59983674-80f8f600-95f0-11e9-962a-e38832e80b96.png)
(Picture of ALL the trash cans supposed to be picked up with arrows above them while being told to return to HQ)
![image](https://user-images.githubusercontent.com/49964391/59983688-a0901e80-95f0-11e9-8ca3-46371ec86847.png)

Trip 3: 
Distance 0.92m
Instant 'Return to HQ' - Hadn't even got out of the truck yet.
![image](https://user-images.githubusercontent.com/49964391/59983746-55c2d680-95f1-11e9-84e2-33e0c320642b.png)

Trip 4:
Distance 0.84m
Instant 'Return to HQ' - Hadn't even got out of the truck yet.
![image](https://user-images.githubusercontent.com/49964391/59983885-53ad4780-95f2-11e9-9951-816e0cfb7b16.png)
(Truck didn't even despawn after this trip. I still have the keys.)
![image](https://user-images.githubusercontent.com/49964391/59983941-ca4a4500-95f2-11e9-85d1-e5cbd213e206.png)

Trip 5:
Distance 0.54m
Instant 'Return to HQ' - Hadn't even got out of the truck yet.
![image](https://user-images.githubusercontent.com/49964391/59983958-ffef2e00-95f2-11e9-9ed6-effae4bcf42b.png)

Total cash earned after 5 trips: $0

**Comment by InZidiuZ** [comment] 2019-06-24 00:18
Interesting, and also wtf, but will investigate tomorrow

**Comment by iMStokes** [comment] 2019-06-25 19:55
This is still going on. Was going to post about it but did see this already handled it. 

I was unsure if the job was bugged or had a cooldown.  

Same situation: I can get my first trip and return to the HQ with no issue.  Get paid.  Opt to start another one, and it will send me to the location to gather.   Once I even get close, it will ping me back to the HQ. I arrive.  Deliver the 0 trash.  And the HQ GPS will stick to my map for the remainder of the day until I relog.

Can also provide screenshots later if needed once I do it again for my 1 check.

**Comment by InZidiuZ** [comment] 2019-06-26 20:34
Added an extreme amount of logging for this now, and also a bunch of changes, so let's see how it works out after the next patch. If it's still fucked, then I'll need some logs so I can see what's happening. :)

**Comment by InZidiuZ** [comment] 2019-06-26 22:38
This is fixed, closing.

**Closed by InZidiuZ** 2019-06-26 22:38 UTC
Labels: enhancement

**Comment by essjaybee** [comment] 2019-06-26 22:47
so garbage changes, everything worked great. I am return to hq, go to HQ, don't get a prompt to E. have the truck still and prompt is to start the job. last thing in log was "just finished all 7 bags, hopefully :)"

and this on log upon approaching recycling, nothing else.

![20190627004626_1](https://user-images.githubusercontent.com/2750716/60220074-1efcf280-9875-11e9-94ff-d7b258e06980.jpg)

**Comment by InZidiuZ** [comment] 2019-06-26 22:49
This would just be a one-time-issue, restarted the script while it was live to push a minor nerf, so that's why^

**Comment by essjaybee** [comment] 2019-06-26 22:50
Oh roger.
