### ISSUE TITLE
NEWS REPORTER CAMERA/BOOM ARM BUG

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-bug-tracker#58] opened 2019-06-22 09:27 UTC
For some reason the camera and boom mic will get stuck in my hand (only from my view, others can't see them) Also people can't see the camera/boom mic in my hand during my filming

**Comment by InZidiuZ** [comment] 2019-06-23 02:25
Hey,

I'm unable to replicate this on my side, which is why I will require more information to properly be able to investigate this.

* Do /info in-game and attach a screenshot of it here.
* Have you been able to reproduce it?
* Can you try to clear your cache and then see if it still happens?
* If able to reproduce it, please attach a screenshot of your F8 console.

**InZidiuZ**
*OP-FW Developer*

**Comment by SoniMatt** [comment] 2019-06-23 09:31
https://imgur.com/a/tiOVg5T screenshots, clearing cache didn't work

**Comment by InZidiuZ** [comment] 2019-06-23 16:43
I've made some changes as to how the objects are spawned and deleted, but still not able to reproduce it, so not able to confirm whether this will resolve the issue or not.

Please take a look after next patch, and let me know if you're still having the same issue.

**Comment by InZidiuZ** [comment] 2019-06-24 16:27
Have you been able to test it out after the latest patch?

**Comment by InZidiuZ** [comment] 2019-06-25 17:25
Will assume this has been resolved, so closing this. If it's still an issue, please create another issue.

**Closed by InZidiuZ** 2019-06-25 17:25 UTC
Labels: bug
