### ISSUE TITLE
When moving cursor in inventory, my POV also changes.

### ISSUE THREAD

**Issue by CheatInNeed** [InZidiuZ/op-framework-bug-tracker#134] opened 2019-07-01 00:53 UTC
**Reporter:**
My name is Peter and i have been playing on Legacy for good 6 months.

**Summary:**
So im experienceing a bug, when im in my inventory and move my cursor, f.ex. to grab a thing and then throw it, i punch and my POV changes.

**Steps to Reproduce:**
It needs to be fixed, because i am quite annoyed of it now, that i have had it for some days.

**Expected Results:**
For me to get it fixed.

**Actual Results:**
Nothing, can't seem to fix it. No staff have seen this before.

## Additional Information

**Screenshots:**
https://youtu.be/yRxzTKXxG6w
Im not quite sure how i would include pictures of my F8 console, since it's going bananas and it's miles long.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment] 2019-07-01 01:01
This has been resolved in DMs, and ended up being caused by an incorrect mouse input method, in GTA settings.

**Closed by InZidiuZ** 2019-07-01 01:01 UTC
Labels: bug
