### ISSUE TITLE
Items disappeared overnight

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/op-framework-bug-tracker#77] opened 2019-06-24 16:37 UTC
Reporter: Blanket - Blanket#0404
Summary: I, along with many others, have experienced an item loss overnight. I logged on today and both my gun and my ID were missing from my trunk. I know others have logged out with items in their inventories and have experienced items missing. This happens both if items are in a trunk OR an inventory. This is the SECOND time this has happened: First I lost a stun gun and food, now I lost my ID and a gun.

Steps to Reproduce: Log out for sleep

Expected Results: What are the expected results? Nothing disappears

Actual Results: What are the actual results? Shit disappears

This is the screenshot that I got, not sure if it's helpful:
![image](https://user-images.githubusercontent.com/49964391/60036280-dd095c00-967c-11e9-9e6d-6c3baf809196.png)

**Comment by InZidiuZ** [comment] 2019-06-24 16:40
Probably related to improper item cleanup on server restart, which might be caused by the recent export issues, which is being investigated.

**Comment by BlankeyBoi** [comment] 2019-06-24 16:41
Neato Mosquito

**Comment by InZidiuZ** [comment] 2019-06-25 21:53
Made a bunch of improvements on the automatic item-cleaner, and this *should* be resolved now. If it isn't related to the item-cleanup which happens on every restart, it'll be some sort of desync between the server & the database, which would be way more complicated.

But, I'm pretty sure it's sorted now. If the issue continues for the next few days, comment here again & I'll reopen the issue.

**Comment by InZidiuZ** [comment] 2019-06-25 23:14
Quick update to this: looks like there's too much data, and whenever the server goes to process it, it times out & deletes random stuff? Weird stuff, but will see if I can find a workaround.

**Comment by InZidiuZ** [comment] 2019-06-26 15:42
Idk I can't decide whether it maybe did work for last restart, gonna close this though, but keep a close eye on it, to make sure it's working properly.

**Closed by InZidiuZ** 2019-06-26 15:42 UTC
Labels: bug
